version: '3.8'

services:
  hestia:
    container_name: hestia_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      VITE_POCKETBASE_URL: http://localhost:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped

  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
      # You can specify the PocketBase version here
      args:
        PB_VERSION: 0.22.12
    ports:
      - "8090:8080" # The port was changed from 8090 to 8080 in the Dockerfile
    volumes:
      - pb_data:/pb/data
    restart: unless-stopped
    healthcheck:
      # The healthcheck now targets port 8080 inside the container
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pb_data:
    name: hestia_pb_data